version: '3.1'

services:

  tomcat:
    image: tomcat:10
    container_name: tomcat

    restart: always

    ports:
      - "8888:8080"

    # volumes:
    #   - ./data/webapps:/usr/local/tomcat/webapps
    #   - ./build/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
